import "./globals.css";
import { Mulish } from "next/font/google";
import { Providers } from "./providers";

const mulish = Mulish({ subsets: ["latin"] });

export const metadata = {
  title: "CoRider Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <meta name="theme-color" content="#fff" />
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
      </head>
      <body className={mulish.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
